train:
  seed: 42
  steps: 500000
  max_episode_steps: 2000
  worker_groups: 1
  workers_per_group: 1
  sim_frequency: 100
  use_history: True
  history_size: 5
  symmetry_augmentation: True
  actor_obs: "normal"
  critic_obs: "normal"
  log_dir: "runs"
  checkpoint_path: "checkpoints/"
  # model_name: "complete_model"
  overwrite_model: true
  model: "d4pg" # Options: sac, ddpg, d4pg, mpo
  
  test_environment: true
  epoch_steps: 1000
  save_steps: 3000
  test_episodes: 2
  show_progress: true
  replace_checkpoint: true

  env_config:
    objective: "target" # Options: walk, target, balance
    reward_scale: 1.0
    # Rewards
    # reward_weights:
    #   survived: 0.001
    #   velocity: 0.15
    #   ang_vel_tracking: 0.05
    #   height_vel_tracking: 0.05
    #   height: 0.1
    #   stall: 0.1
    #   torque: 0.01
    #   action_diff: 0.01
    #   acceleration: 0.05
    #   flat_orientation: 0.04
    #   feet_flat: 0.3
    #   base_stability: 0.05
    #   feet_airtime: 0.1
    #   torso_centering: 0.1
    #   termination: -0.05
    reward_weights:
      survived: 0.001
      velocity: 0.6        # much larger
      ang_vel_tracking: 0.1
      height_vel_tracking: 0.00
      height: 0.05
      stall: 1          # larger negative impact (note stall returns -1 when triggered)
      torque: 0.01       # negative weight, or use penalty function and positive weight
      action_diff: 0.002
      acceleration: 0.0002
      flat_orientation: 0.01
      feet_flat: 0.1
      base_stability: 0.02
      feet_airtime: 1.0
      torso_centering: 0.05
      joint_deviation: 0.02
      termination: -1.0    # larger negative impact
      
    # Commands
    commands:
      base_velocity:
        ranges:
          lin_vel_x: [-0.2, 0.3]
          lin_vel_y: [-0.2, 0.2]
          ang_vel_z: [-0.1, 0.1]

    # Randomization & Events
    enable_perturbations: True
    push_interval_s: 3.0
    push_vel_range: 1.0
    
    enable_physics_randomization: True
    events:
      reset_base:
        params:
          pose_range:
            x: [-0.5, 0.5]
            y: [-0.5, 0.5]
            yaw: [-3.14, 3.14]
          velocity_range:
            x: [-0.1, 0.1]
            y: [-0.1, 0.1]
            z: [-0.1, 0.1]
            roll: [-0.1, 0.1]
            pitch: [-0.1, 0.1]
            yaw: [-0.1, 0.1]
      reset_robot_joints:
        params:
          position_range: [-0.1, 0.1]
          velocity_range: [0.0, 0.0]
      push_robot:
        interval_range_s: [3.0, 6.0]
        params:
          velocity_range:
            x: [-0.3, 0.3]
            y: [-0.3, 0.3]
      randomize_mass:
        params:
          mass_distribution_params: [-0.2, 0.2]
          operation: "add"
      randomize_friction:
        params:
          static_friction_range: [0.5, 1.5]
          dynamic_friction_range: [0.5, 1.5]
          restitution_range: [0.0, 0.0]
          num_buckets: 64

    # Noise
    observation_noise_model:
      mean: 0.0
      std: 0.00
    action_noise_model:
      mean: 0.0
      std: 0.00

model:
  # Network configuration
  actor_config:
    network_type: transformer # Options: mlp, cnn, lstm, transformer
    d_model: 256
    nhead: 4
    num_layers: 2
    dim_feedforward: 1024
    # hidden_sizes: [1024,512,256]
    
  critic_config:
    network_type: transformer # Options: mlp, cnn, lstm, transformer
    d_model: 256
    nhead: 4
    num_layers: 2
    dim_feedforward: 1024
    # hidden_sizes: [1024,512,256]
    
  # Training params
  target_coeff: 0.005
  actor_lr: 1e-4
  critic_lr: 1e-4
  lr_scheduler:
    T_max: 5e5
    eta_min: 1.0e-5

buffer:
  size: 1000000
  return_steps: 3
  batch_iterations: 10 # Match replay ratio of ~0.4 (100 updates / 256 transitions)
  batch_size: 2048
  discount_factor: 0.99
  steps_before_batches: 4096 # Start training after 1 step
  steps_between_batches: 1 # Update every step
  seed: 42
