# File to train with history models like in the paper:
# https://journals.sagepub.com/doi/full/10.1177/02783649241285161
train:
  seed: 42
  steps: 2000000
  max_episode_steps: 2000
  worker_groups: 1
  workers_per_group: 8
  sim_frequency: 50
  use_history: True
  short_history_size: 4
  long_history_size: 0
  log_dir: runs_history_tests
  checkpoint_path: checkpoints_history_tests/
  model_name: history_no_long
  overwrite_model: False

  model: d4pg

  test_environment: False
  epoch_steps: 5e3
  save_steps: 5e4

  test_episodes: 5
  show_progress: True
  replace_checkpoint: False
  log: True

model:
  actor_sizes: [[256, 256], [[6, 32, 3], [4, 16, 2]]]
  critic_sizes: [[256, 256], [[6, 32, 3], [4, 16, 2]]]
  target_coeff: 0.005
  actor_lr: 1e-4
  critic_lr: 1e-4
  lr_scheduler:
    T_max: 5e5
    eta_min: 1e-5

buffer:
  size: 1e5
  return_steps: 1
  batch_iterations: 50
  batch_size: 1024
  discount_factor: 0.99
  steps_before_batches: 1e4
  steps_between_batches: 50
  seed: 42
