train:
  seed: 42
  steps: 20000000
  max_episode_steps: 4000
  worker_groups: 1
  workers_per_group: 8
  sim_frequency: 100
  use_history: False
  short_history_size: 0
  long_history_size: 0
  log_dir: runs_optimizers_tests
  checkpoint_path: checkpoints_optimizers_tests/
  model_name: d4pg_com_center
  overwrite_model: False

  model: d4pg

  test_environment: False
  epoch_steps: 5e3
  save_steps: 5e4

  test_episodes: 5
  show_progress: True
  replace_checkpoint: False
  log: True

model:
  actor_sizes: [256, 256]
  critic_sizes: [256, 256]
  target_coeff: 0.005
  actor_lr: 1e-3
  critic_lr: 1e-3
  lr_scheduler:
    T_max: 5e5
    eta_min: 1e-5

buffer:
  size: 1e6
  return_steps: 5
  batch_iterations: 50
  batch_size: 1024
  discount_factor: 0.99
  steps_before_batches: 1e4
  steps_between_batches: 50
  seed: 42
