train:
# 209495
  seed: 42
  steps: 30000000
  max_episode_steps: 1000
  worker_groups: 8
  workers_per_group: 16
  sim_frequency: 100
  use_history: False
  short_history_size: 0
  long_history_size: 0
  log_dir: runs_final
  checkpoint_path: checkpoints_final/
  model_name: mpo
  overwrite_model: False

  model: mpo

  test_environment: False
  epoch_steps: 5e3
  save_steps: 1e5

  test_episodes: 5
  show_progress: False
  replace_checkpoint: False
  log: True

model:
  actor_sizes: [256, 256]
  critic_sizes: [256, 256]
  target_coeff: 0.005
  actor_lr: 1e-4
  critic_lr: 1e-4
  lr_scheduler:
    T_max: 5e5
    eta_min: 1e-5

buffer:
  size: 1e6
  return_steps: 5
  batch_iterations: 50
  batch_size: 1024
  discount_factor: 0.99
  steps_before_batches: 1e4
  steps_between_batches: 50
  seed: 42
